# Generated by Django 4.2.20 on 2025-03-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_name', models.CharField(max_length=30)),
                ('pat_num', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=30)),
            ],
        ),
    ]
